[package]
name = "rust_viczesimal"
version = "1.0.0"
description = "Calculates viczesimal numbers"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"] 
